# 현재 활성화된 프로파일을 'local'로 설정
spring:
  profiles:
    active: local  # 현재 활성화된 프로파일: 'local'
    group:
      # 각 프로파일에 따라 활성화될 프로파일들을 설정
      local: local_server, common, secret  # 'local' 프로파일은 'local_server', 'common', 'secret' 프로파일 활성화
      blue: blue_server, common, secret   # 'blue' 프로파일은 'blue_server', 'common', 'secret' 프로파일 활성화

---
# 'local_server' 프로파일에 해당하는 설정
spring:
  config:
    activate:
      on-profile: local_server  # 'local_server' 프로파일 활성화 시 적용되는 설정
server:
  port: 8080  # 로컬 서버 포트 설정
react:
  server:
    protocol: http  # 프로토콜: http
    host: localhost  # 호스트: localhost
    port: 5173  # 포트: 5173

---
# 'blue_server' 프로파일에 해당하는 설정
spring:
  config:
    activate:
      on-profile: blue_server  # 'blue_server' 프로파일 활성화 시 적용되는 설정
server:
  port: 8080  # 서버 포트 설정
react:
  server:
    protocol: https  # 프로토콜: https
    host: ??? ?? ?? ??(ip ?? ???)  # 호스트를 IP로 설정해야 하며, 해당 IP를 여기에 넣어야 함
    port: 5173  # 포트: 5173

---
# 'common' 프로파일에 해당하는 설정
spring:
  config:
    activate:
      on-profile: common  # 'common' 프로파일 활성화 시 적용되는 설정
mybatis:
  mapper-locations:
    - /mappers/*.xml  # MyBatis 매퍼 파일 경로 설정
    - /mappers/user/*.xml  # 추가적인 MyBatis 매퍼 파일 경로 설정
