spring:
  config:
    import: application-secret.yml
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

# mybatis : Java 애플리케이션에서 SQL을 쉽게 사용할 수 있도록 도와주는 프레임워크
mybatis:
  mapper-locations:
    - /mappers/*.xml # mappers안에 있는 모든 .xml 파일을 mapper로 등록
    - /mappers/book/*.xml
    - /mappers/user/*.xml
    - /mappers/post/*.xml

logging:
  config: classpath:log4j2.xml
  file:
    path: logs


oauth2:
  client:
    redirect_uri: http://localhost:3000/oauth2